[workspace]
members = [
    "1_concepts",
    "1_concepts/1_*",
    "2_idioms",
    "2_idioms/2_*",
    "3_ecosystem",
    "3_ecosystem/3_*",
    "4_backend",
    "4_backend/4_*",
    "rust_by_examples",
    "asynchronous_programming",
    "asynchronous_programming/hello-async",
    "asynchronous_programming/concurrency-with-async",
    "asynchronous_programming/any_futures",
    "asynchronous_programming/futures_sequence",
    "asynchronous_programming/mix_async",
    "asynchronous_programming/all_together_async",
]
