# Количество одновременно обрабатываемых картинок от 1 до 10_000
img_concurrency = 16

# Выходной директорий для хранения оброботанных картинок
img_output_dir = "img_output"

# Качество обрабатываемых картинок от 1 до 100
img_quality = 30

# Ограничение скорости загрузки изображений в KiB, значение 0 - отсутствие ограничений
rate_limit = 100

# Timeout для загрузки одного изображения в секундах от 1 до 255
time_out = 35