[package]
name = "step_3_9"
version = "0.1.0"
edition = "2024"
publish = false
homepage = "https://artaudiochats.t.me/"


[dependencies]
clap = { version = "4.5.5", features = ["derive", "env"] }
serde = { version = "1.0.228", features = ["derive"]}
thiserror = "1.0"      # Для макроса #[derive(thiserror::Error)]
toml = "0.8"           # Для toml::de::Error (используется в коде)
