[mode]
# Режим отладки включает дополнительное логирование, трассировку и профилирование
# для упрощения разработки и отладки приложения.
#
# Default:
debug = false




[server]
# URL-адрес, по которому данное приложение доступно извне.
#
# Default:
external_url = "http://127.0.0.1"

# Порт, предоставляющий HTTP-интерфейс клиентам.
# Этот порт должен быть доступен извне.
#
# Default:
http_port = 8081

# Порт, предоставляющий клиентам доступ к gRPC-интерфейсу (Google Remote Procedure Call).
# Этот порт должен быть доступен извне.
#
# Default:
grpc_port = 8082

# Порт, обеспечивающий HTTP-проверку работоспособности приложения.
# Этот порт должен быть доступен только внутри Kubernetes Pod.
# Pod в Kubernetes — это наименьшая, базовая развертываемая 
# вычислительная единица, представляющая собой группу из одного или 
# нескольких контейнеров (например, Docker), объединенных общим 
# хранилищем, IP-адресом и сетевым пространством. Поды — это логический 
# хост, где контейнеры работают совместно на одном узле (Node), разделяя 
# ресурсы. 
# Pod - стручёк
#
# Default:
healthz_port = 10025

# Порт, предоставляющий конечную точку для сбора метрик Prometheus.
# Этот порт должен быть доступен только внутри кластера Kubernetes.
#
# Default:
metrics_port = 9199


[db.mysql]
# Хост сервера базы данных MySQL.
#
# Default:
host = "127.0.0.1"

# Порт, на котором сервер базы данных MySQL принимает соединения.
#
# Default:
port = 3306

# Имя базы данных для использования на сервере MySQL.
#
# Default:
dating = "default"

# Пользователь базы данных MySQL для подключения к серверу MySQL.
#
# Default:
user = "root"

# Пароль пользователя базы данных MySQL, используемый для аутентификации на сервере MySQL.
#
# Default:
pass = "root"

[db.mysql.connections]
# Максимально допустимое количество соединений в пуле неактивных соединений.
#
# Значения, превышающие connections.max_open, будут автоматически уменьшены
# до значения, соответствующего пределу connections.max_open.
#
# Default:
max_idle = 30

# Максимально допустимое количество открытых соединений с сервером базы данных MySQL 
# одновременно.
#
# Default:
max_open = 30




[log.app]
# Максимально допустимый уровень записей в логе приложения.
#
# Возможные значения (в порядке возрастания):
#   "error", "warn", "info", "debug", "trace"
#
# Default:
level = "info"




[background.watchdog]
# Период времени для запуска фоновой задачи мониторинга.
#
# Default:
period = "5s"

# Максимальное количество записей, которые могут быть завершены за один запуск задания.
#
# Default:
limit = 10

# Тайм-аут для удержания сторожевой блокировки записей.
#
# Default:
lock_timeout = "4s"
