[package]
name = "step_3_11"
version = "0.1.0"
edition = "2024"
publish = false
homepage = "https://artaudiochats.t.me/"
authors = ["Arthur Pronota <yhgvnhjk.986ght.jhgt543@gmail.com>"]

[dependencies]
num_cpus = "1.0"
clap = { version = "4.5.5", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3.32"
reqwest = "0.13.2"


